/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PushLogService } from "../pushLog.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PushLogCreateInput } from "./PushLogCreateInput";
import { PushLog } from "./PushLog";
import { PushLogFindManyArgs } from "./PushLogFindManyArgs";
import { PushLogWhereUniqueInput } from "./PushLogWhereUniqueInput";
import { PushLogUpdateInput } from "./PushLogUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PushLogControllerBase {
  constructor(
    protected readonly service: PushLogService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PushLog })
  @nestAccessControl.UseRoles({
    resource: "PushLog",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPushLog(
    @common.Body() data: PushLogCreateInput
  ): Promise<PushLog> {
    return await this.service.createPushLog({
      data: {
        ...data,

        message: data.message
          ? {
              connect: data.message,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        errorInfo: true,
        id: true,

        message: {
          select: {
            id: true,
          },
        },

        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PushLog] })
  @ApiNestedQuery(PushLogFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PushLog",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async pushLogs(@common.Req() request: Request): Promise<PushLog[]> {
    const args = plainToClass(PushLogFindManyArgs, request.query);
    return this.service.pushLogs({
      ...args,
      select: {
        createdAt: true,
        errorInfo: true,
        id: true,

        message: {
          select: {
            id: true,
          },
        },

        status: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PushLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PushLog",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async pushLog(
    @common.Param() params: PushLogWhereUniqueInput
  ): Promise<PushLog | null> {
    const result = await this.service.pushLog({
      where: params,
      select: {
        createdAt: true,
        errorInfo: true,
        id: true,

        message: {
          select: {
            id: true,
          },
        },

        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PushLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PushLog",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePushLog(
    @common.Param() params: PushLogWhereUniqueInput,
    @common.Body() data: PushLogUpdateInput
  ): Promise<PushLog | null> {
    try {
      return await this.service.updatePushLog({
        where: params,
        data: {
          ...data,

          message: data.message
            ? {
                connect: data.message,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          errorInfo: true,
          id: true,

          message: {
            select: {
              id: true,
            },
          },

          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PushLog })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PushLog",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePushLog(
    @common.Param() params: PushLogWhereUniqueInput
  ): Promise<PushLog | null> {
    try {
      return await this.service.deletePushLog({
        where: params,
        select: {
          createdAt: true,
          errorInfo: true,
          id: true,

          message: {
            select: {
              id: true,
            },
          },

          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
